services:
    App\EventListener\CorsSubscriber:
        tags: [] 

    App\EventListener\JwtLoginResponseListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success }
